# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0

definitions:
  steps:
    - step: &testing
        name: Test
        caches:
          - composer
        script:
          - composer install
          - ./vendor/bin/phpunit --configuration phpunit.xml --log-junit ./test-reports/composer-report.xml
        artifacts:
          - ./test-reports/*
    - step: &code-quality
        name: Code-Quality
        image: php:8.0
        script:
          - mkdir -p ./test-reports/ ./tmp/phpcs/
          - curl -L https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -o ./tmp/phpcs.phar
          - chmod u+x ./tmp/phpcs.phar
          - ./tmp/phpcs.phar -sw --standard=phpcs.xml  --report=checkstyle --report-file=./test-reports/checkstyle-result.xml
        # PHPmd
        # vendor/bin/phpcpd
        after-script:
          - pipe: atlassian/checkstyle-report:0.2.1
        artifacts:
          - ./test-reports/*

pipelines:
  branches:
    master:
      - step:
          name: Upgrade patch version
          script:
            - OLD_VERSION=$(cat composer.json | grep version | head -1 | awk -F":" '{print $2}' | sed 's/[",]//g' | tr -d '[[:space:]]')
            - NEW_VERSION=$(echo $OLD_VERSION | awk -F. '{ print $1"."$2"."$3+1 }')
            - sed -i 's|'"${OLD_VERSION}"'|'"${NEW_VERSION}"'|g' composer.json
            - git add composer.json
            - git commit -m 'Upgrade to '"${NEW_VERSION}"' [skip ci]'
            - git tag v$NEW_VERSION
            - git push && git push --tags
  pull-requests:
    '**':
      - step: *testing
      - step: *code-quality