---
version: 2

variables:
  version: 0.1.6
  repositoryUsername: EMalyj
  repositoryPassword: BAMSCRT@0@0@x7nannRBRK1+k8GFESFQrg==
  projectName: laravel-survey

plan:
  project-key: LVLSUR
  key: TAP
  name: Test and publish

stages:
  - Run tests:
      jobs:
        - Run PHPUnit
  - Publish code:
      jobs:
        - Publish to repository

Run PHPUnit:
  tasks:
    - clean
    - script: composer install
    - script: ./vendor/bin/phpunit --log-junit ./test-reports/phpunit.xml
  final-tasks:
    - test-parser:
        type: junit
        test-results: "**/test-reports/*.xml"
  requirements:
    - Composer

Publish to repository:
  tasks:
    - script:
        - rm -rf bamboo-specs
        - rm composer.lock
        - rm phpunit.xml
        - zip -r ${bamboo.projectName} *
        - curl -v --user '${bamboo.repositoryUsername}:${bamboo.repositoryPassword}' --upload-file ${bamboo.projectName}.zip https://registry.kuhdo.de/repository/packages/packages/upload/kuhdo/${bamboo.projectName}/${bamboo.version}
