project:
  key: LVLSUR
  plan:
    key: TAP
    name: Test
stages:
  - jobs:
      - scripts:
          - composer install
          - ./vendor/bin/phpunit --log-junit test-reports/phpunit.xml
        requirements:
          - Composer
        testParsers:
          - junit
