---
version: 2
plan:
  project-key: LVLSUR
  key: TAP
  name: Test

stages:
  - Run tests:
      jobs:
        - Run PHPUnit
  - Publish code:
      jobs:
        - Publish to repository

Run PHPUnit:
  tasks:
    - clean
    - script: composer install
    - script: ./vendor/bin/phpunit --log-junit ./test-reports/phpunit.xml
  final-tasks:
    - test-parser:
        type: junit
        test-results: "**/test-reports/*.xml"
  requirements:
    - Composer

Publish to repository:
  tasks:
    - script: ls
