project:
  key: LVLSUR
  plan:
    key: TAP
    name: Test
stages:
  - jobs:
      - scripts:
          - composer install
          - composer test
        requirements:
          - composer
        testParsers:
          - phpunit
