project:
  key: LVLSUR
  plan:
    key: TAP
    name: Test
stages:
  - jobs:
      - scripts:
          - echo 'test'
          - composer install
          - composer test
      - requirements:
          - composer
      - artifacts:
          - name: Laravel survey data
