---
version: 2
plan:
  project-key: LVLSUR
  key: TAP
  name: Test

stages:
  - Run tests:
      jobs:
        - Install dependencies
        - Run PHPUnit

Install dependencies:
  tasks:
    - script: composer install
  requirements:
    - Composer

Run PHPUnit:
  tasks:
    - script: ./vendor/bin/phpunit --log-junit ./test-reports/phpunit.xml
  final-tasks:
    - test-parser:
        type: junit
        test-results: "**/test-results/*.xml"
  requirements:
    - Composer
